project:
  type: book
  output-dir: book

book:
  title: "Onderzoeksleerlijn HAN Bedrijfskunde"
  author: "Yvonne Peterman & Witek ten Hove"
  date: "2/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

