project:
  type: book
  output-dir: book

book:
  title: "Onderzoeksleerlijn HAN Bedrijfskunde"
  author: "Yvonne Peterman & Witek ten Hove"
  date: "2/1/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - cultuur.qmd
    - docent.qmd
    - student.qmd
    - praktijk.qmd
    - curriculum.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    include-before-body: header.html
    include-after-body: scripts.html

  pdf:
    documentclass: scrreprt

editor: visual