---
jupyter: envpy39
---

# Cultuurontwikkeling binnen de opleiding

Hier beschrijf je de actiepunten gericht op cultuurontwikkeling...

Kenmerken van constructivistische leeromgevingen [@jonassen1994]:

1.  Bied diverse representaties uit het echte leven om overmatige simplificatie te vermijden.

2.  Geef de natuurlijke complexiteit van de werkelijkheid weer.

3.  Benadruk de creatie van kennis, in plaats van een replicatie van kennis.

4.  Accentueer het gebruik van echte opdrachten die direct toepasbaar zijn, in tegenstelling tot vage en abstracte aanwijzingen, binnen het kader van constructivistisch leren.

5.  Creëer leeromgevingen die de echte wereld of praktijkgevallen nabootsen, in plaats van het volgen van vastgestelde instructiereeksen.

6.  Stimuleer diepgaande reflectie op ervaringen.

7.  Bied ruimte voor context- en inhoud-afhankelijke kennisconstructie.

8.  Ondersteun samenwerkingsgerichte kenniscreatie door sociale samenwerking, zonder competitie tussen gebruikers aan te moedigen.

Visie op leren [@schneckenberg2011web]:

-   Leren is alomtegenwoordig. Het vindt plaats in verschillende contexten.

-   Lerenden worden geleidelijk de organisatoren van hun eigen leerproces.

-   Leren is levenslang proces en vindt slechts voor een beperkt gedeelte plaats binnen het onderwijs.

-   Leren is een collaboratief proces en vindt plaats binnen communities.

-   Leren is een informeel proces en vindt plaats op verschillende plekken en momenten.\
    \

```{=html}
<div class="ratio ratio-16x9">
              <iframe
                width="560"
                height="315"
                src="https://www.youtube.com/embed/VAq7qJ2nzAQ?si=6dSSGMidWUQIXhQu"
                title="YouTube video player"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                allowfullscreen
              ></iframe>
            </div>
```
## Actiepunten cultuurontwikkeling

|     | Actiepunt   | Beschrijving                 | NB   |
|-----|-------------|------------------------------|------|
| 1   | Actiepunt 1 | Beschrijving van actiepunt 1 | NB 1 |
